config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  # Defines the root path route ("/")
  root to: "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  namespace :api do
    resources :users do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
    return if user.blank?

    can :destroy, Post do |post|
      post.author == user || user.role == 'admin'
    end

    can :destroy, Comment do |comment|
      comment.author == user || user.role == 'admin'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.update(commentsCounter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.update(likesCounter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes
  has_many :comments
  belongs_to :author, class_name: 'User'

  validates :title, presence: true, length: { maximum: 250 }
  validates :commentsCounter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likesCounter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def five_most_recent_comments
    Comment.includes(:post).where(post_id: id).order(created_at: :desc).limit(5)
  end

  after_save :update_posts_counter

  private

  def update_posts_counter
    author.update(postsCounter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  validates :postsCounter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def three_most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  def index
    @post = Post.find(params[:post_id])
    @comments = Comment.where(post_id: @post.id)

    render json: @comments
  end

  def create
    @comment = Comment.new(params.require(:comment).permit(:text))
    @comment.post = Post.find(params[:post_id])
    @comment.author = current_user

    if @comment.save
      render json: @comment
    else
      render json: @comment.errors
    end
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = Post.includes(:author).where(author_id: params[:user_id])

    render json: @posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @user = Post.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new(params.require(:comment).permit(:text))
    @comment.author = current_user
    @comment.post = @post

    if @comment.save
      redirect_to user_post_path(@user, @post)
    else
      render :new
    end
  end

  def destroy
    @comments = Comment.find(params[:id])
    @comments.destroy
    redirect_to user_post_url
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = Post.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @like = Like.new
    @like.author = current_user
    @like.post = @post

    if @like.save
      redirect_to user_post_path(@user, @post)
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(params[:user_id])
    @posts = Post.includes(:author).where(author_id: params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.author_id)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(form_params.merge(author: current_user, likesCounter: 0, commentsCounter: 0))

    if @post.save
      redirect_to user_posts_url
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_posts_path
  end

  private

  def form_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.three_most_recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= form_with model: @comment, url: user_post_comments_path do |f| %>
  <%= f.text_field :text %>
  <%= f.submit "Add comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/partials/_post_card.html.erb
<div class='post-card'>
  <h3><%= post.title %></h3>
  <h3><%= post.text %></h3>
  <h5>Comments: <%= post.commentsCounter %>, Likes: <%= post.likesCounter %></h5>
</div>

app/views/partials/_user_card.html.erb
<div class='user-card'>
  <h3 class='profile-pic'><%= user.photo %></h3>
  <div class='user-information'>
    <h2 class='user-name'><%= user.name %></h2>
    <h4 class='user-number-of-posts'>Number of posts: <%= user.postsCounter %></h4>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'partials/user_card', user: @user %>
<ul class='posts-list'>
  <% @posts.each do |post| %>
    <li>
      <%= link_to "/users/#{@user.id}/posts/#{post.id}" do %>
        <%= render 'partials/post_card', post: post %>
      <% end %>
      <% if post.commentsCounter > 0 %>
        <div class='comments-box'>
          <% @comments = post.five_most_recent_comments %>
          <% @comments.each do |comment| %>
            <% @users = User.where(id: comment.author_id) %>
            <% @users.each do |user| %>
              <h4><%= user.name %>: <%= comment.text %></h4>
            <% end %>
          <% end %>
        </div>
      <% else %>
        <div class='comments-box'>No comments yet</div>
      <% end %>
    </li>
  <% end %>
</ul>
<button class='pagination-button'>Pagination</button>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_with model: @post, url: user_posts_path do |f| %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <%= f.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<div class='post'>
  <div class='post-header'>
    <h3><%= @post.title %> by <%= @user.name %></h3>
    <h5>Comments: <%= @post.commentsCounter %>, Likes: <%= @post.likesCounter %></h5>
  </div>
  <h3><%= @post.text %></h3>
</div>
<% if @post.commentsCounter > 0 %>
  <div class='post-comments'>
    <% @comments = Comment.where(post_id: @post.id) %>
    <% @comments.each do |comment| %>
      <% @users = User.where(id: comment.author_id) %>
      <% @users.each do |user| %>
        <div class='comment-item'>
          <h4><%= user.name %>: <%= comment.text %></h4>
          <% if can? :destroy, comment %>
            <%= button_to 'Delete comment', user_post_comment_url(comment.author, @post, comment), method: :delete %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
<% else %>
  <div class='post-comments'>No comments yet</div>
<% end %>
<%= form_with model: Like, url: user_post_likes_path(@user, @post) do |f| %>
  <%= f.submit "Add like!" %>
<% end %>
<% if can? :destroy, @post %>
  <%= button_to 'Delete post', user_post_path, method: :delete %>
<% end %>

app/views/users/index.html.erb
<ul class='user-list'>
  <% @users.each do |user| %>
    <%= link_to user_path(user.id) do %>
      <li><%= render 'partials/user_card', user: user %></li>
    <% end %>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= render 'partials/user_card', user: @user %>
<div class='user-bio'>
  <h3>Bio</h3>
  <h3><%= @user.bio %></h3>
</div>
<ul class='thre-posts-list'>
  <% @posts.each_with_index do |post, index| %>
    <li><%= render 'partials/post_card', post: post, index: index %></li>
  <% end %>
</ul>
<%= link_to user_posts_path(@user) do %>
  <button class='all-posts-button'>See all posts</button>
<% end %>